Repository auro-dev/django-basics-1, pull requests merged in 2022-10, with the labels that each got.

#1 User Post service added with models, views etc
  README.md
  profiles_api/models.py
  profiles_api/serializers.py
  profiles_api/urls.py
  profiles_api/views.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED, hacktoberfest22, ready-to-merge

#2 City service added with model, views etc
  profiles_api/models.py
  profiles_api/serializers.py
  profiles_api/urls.py
  profiles_api/views.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED, hacktoberfest22, ready-to-merge, clean-code

#3 Friend request service created with required views, models etc
  profiles_api/models.py
  profiles_api/urls.py
  profiles_api/views.py
Labels: enhancement, hacktoberfest, HACKTOBERFEST-ACCEPTED, hacktoberfest22, clean-code

#4 Hash Tags service added with views, models etc
  profiles_api/models.py
  profiles_api/serializers.py
  profiles_api/urls.py
  profiles_api/views.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED, hacktoberfest22, ready-to-merge, clean-code
